### ISSUE TITLE
Plugin does not pickup the latest Arduino SDK on Mac OS X

### ISSUE THREAD

**Issue by zmitrok** [francoiscampbell/CLionArduinoPlugin#1]
I had to edit the ArduinoToolchain.cmake and add `Arduino.app/Contents/Java/` to the existing `Arduino.app/Contents/Resources/Java/` to fix the "set ARDUINO_SDK" error message.

**Comment by francoiscampbell** [comment]
Give this release a shot: [https://github.com/francoiscampbell/CLionArduinoPlugin/releases/tag/v1.1.0](https://github.com/francoiscampbell/CLionArduinoPlugin/releases/tag/v1.1.0)

**Comment by zmitrok** [comment]
1.1.0 release works. Thanks!

**Comment by zmitrok** [comment]
btw, you might want to update the plugin version in the plugin.xml. 1.1.0 shows up as 1.0.2

**Comment by francoiscampbell** [comment]
Done. you can grab the zip in the Releases section or wait for JetBrains to approve it.
