### ISSUE TITLE
On Mac OS X, the hardware platform needs to be registered explicitly

### ISSUE THREAD

**Issue by zmitrok** [francoiscampbell/CLionArduinoPlugin#2]
In my CMakeLists.txt file I had to invoke `register_hardware_platform(/Applications/Arduino.app/Contents/Java/hardware/arduino/avr)` before the generate_arduino_firmware function invocation.

**Comment by francoiscampbell** [comment]
The test build I gave you in #1 should fix this also.

**Comment by zmitrok** [comment]
confirmed, with 1.1.0 I didn't have to register the hardware platform directory. Was able to build the same project with both 'uno' and 'LilyPadUSB' board IDs.
