### ISSUE TITLE
Upload Support

### ISSUE THREAD

**Issue by nat45928** [francoiscampbell/CLionArduinoPlugin#3]
Anny plan to introduce upload support into the UI?

**Comment by francoiscampbell** [comment]
I replied here: [https://www.reddit.com/r/arduino/comments/3fvrys/introducing_the_clion_arduino_plugin/ctv12hr](https://www.reddit.com/r/arduino/comments/3fvrys/introducing_the_clion_arduino_plugin/ctv12hr)
