### ISSUE TITLE
Please update README with simple steps to get existing Arduino project imported

### ISSUE THREAD

**Issue by kigster** [francoiscampbell/CLionArduinoPlugin#7]
A lot of things were new and not obvious to me, coming from C++/Arduino background, and Eclipse IDE with Arduino plugin (which I still use and love).

I would imagine most people trying this will have existing projects. These projects will depend on external private libraries, various board types, and require compiling, resolving issues, and uploading to the board itself.  

It would be amazing to have simple instructions on how to do that for a noob to CMake.

Thanks!

**Comment by francoiscampbell** [comment]
Project import via the GUI is on the way. If you have 3rd party libs in the libraries folder and the Arduino IDE picks them up, then CMake should too. I'll investigate if that's not the case.

**Comment by kigster** [comment]
Gotcha, so I am NOT actually using Arduino IDE.  I install it, and then typically use Eclipse IDE + Eclipse Arduino plugin.

**Comment by kigster** [comment]
Would you be interested in any help? Is there an easy way to split the project into non-overlapping features? I am very comfortable with IntelliJ platforms (IDEA since 2005, RubyMine since pre-release, and CLion since pre-release).  I've never written a plugin but I am sure I can pick it up quick.

**Comment by francoiscampbell** [comment]
Yeah, I'd love some help. Like I mentioned in #6, I don't have a lot of time to devote to this; I'm a student working full-time on a co-op term. My next goal is to have GUI options to set the firmware and board parameters and not have to go through the CMakeLists.txt file for it.
